spring:
  datasource:
    url: jdbc:postgresql://ec2-54-247-95-125.eu-west-1.compute.amazonaws.com:5432/d1v8vlooa6drf6?user=sorjqytozvhqvm&password=eae342e28b2e88979edd2e2b5ceb6d0996e4e9c3dda13a84b90be3c6936aa731&ssl=true&sslfactory=org.postgresql.ssl.NonValidatingFactory
    tomcat:
      max-active: 15
      max-idle: 15